### ISSUE TITLE
ProgressBars appears unexpectedly

### ISSUE THREAD

**Issue by Ali-Rezaei** [wajahatkarim3/Imagine#69]
When I scroll in order to load next page, and rotate the device, ProgressBars appears unexpectedly and never disappears.

Please look at this : https://drive.google.com/file/d/1o5tM0l2XJLDjaCwL1WvzLqVN7rc5KT0T/view?usp=sharing

Is it related to implementation of Paging library? If yes, which version of library are using in the demo APK file in the readme screen?

**Comment by wajahatkarim3** [comment]
@Ali-Rezaei I can't access the video you shared. Can you upload it directly on Github?

**Comment by Ali-Rezaei** [comment]
Thank you for your swift response. Here you are :

https://user-images.githubusercontent.com/2465559/126140541-ee078122-b6b2-4783-857a-2b7c3920db98.mp4

**Comment by chandmohd** [comment]
Hi,

**Comment by wajahatkarim3** [comment]
Thank you @chandmohd for the PR. I have merged it.
